### ISSUE TITLE
COMSODE logo in footer (static resource) not displayed in some cases

### ISSUE THREAD

**Issue by skrchnavy** [OpenDataNode/ckanext-odn-theme#1]
If ckan installed in an application context ( for example http://xxx/internalcatalog) COMSODE logo displayed correctly.

In case of installation of catalog in root of server (example http://xxx/) then COMSODE logo in footer on first page is correctly displayed. (generated html tag:  `<img src="/base/images/comsodelogo.png" alt="Comsode" border="0" style="margin-top:6px;">`)
 but in subpage (example http://xxx/dataset for datasets list) is not displayed. (generated html tag: `<img src="/datasetbase/images/comsodelogo.png" alt="Comsode" border="0" style="margin-top:6px;">`)

Version: ODN_v0.9.0

**Comment by mvi-eea-sk** [comment]
fixed in 2b21340 and 08f018f
ckan.site_url in .ini file has to be set, when the url to CKAN isn't simple one
