### ISSUE TITLE
Version in header shall not be hardcoded in html

### ISSUE THREAD

**Issue by skrchnavy** [OpenDataNode/ckanext-odn-theme#4]
Currently the version of ODN is displayed in ckanext/odn_theme/templates/header.html so for every ODN release the theme also requires rerelease.

Expected is external configuration from a configuration file (that is not part of the theme).
If such configuration value is not defined, nothing is displayed.

**Comment by skrchnavy** [comment]
Configuration parameter in CKAN configuration file must be added to support this.
`ckan.odn_version = 1.0`

**Comment by mvi-eea-sk** [comment]
https://github.com/OpenDataNode/odn-box/commit/e3d9e5159bf289e560266e0dc3b517a2d481bcdd
DONE, closing
