### ISSUE TITLE
To split odn-theme plugin into plugins for IC and PC

### ISSUE THREAD

**Issue by skrchnavy** [OpenDataNode/ckanext-odn-theme#8]
Currently we have one common plugin for OpenDataNode theme (`odn-theme`). It is required to be able to theme both Internal and Public catalog independently, so 2 plugins shall be added (`odn-theme-ic` and `odn-theme-pc`).
There is also expected common code, so `odn-theme` will be presented and those 2 new themes shall only override snippets/templates/css that are different.

**Comment by mvi-eea-sk** [comment]
@skrchnavy just to be sure, this new plugins should be part of the same ckan extension like this:
- ckanext-odn-theme = CKAN extension
  - odn_theme = one of the plugins inside the extension
  - odn_theme_ic = one of the plugins inside the extension
  - odn_theme_pc = one of the plugins inside the extension

In internal catalog, plugins enabled in production.ini will be:

```
plugins = odn_theme odn_theme_ic ...
```

In public catalog, plugins enabled in production.ini will be:

```
plugins = odn_theme odn_theme_pc ...
```

**Comment by skrchnavy** [comment]
Yes, plugins in same extension and configured in production.ini

**Comment by mvi-eea-sk** [comment]
@skrchnavy i split the themes in branch: feature/split_ic_pc_theme
commit: https://github.com/OpenDataNode/ckanext-odn-theme/commit/f0de88bdc2debec91ef1bff0e88dbfd5e9669f96

reassign the issue to whoever will do the CSS changes

**Comment by skrchnavy** [comment]
@rskultety to test/update
